# word Embedding Tchniques Using Embedding Layer in Keras

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2025-04-09 11:04:03.781469: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-04-09 11:04:03.793482: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1744175943.808359     785 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1744175943.812673     785 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-04-09 11:04:03.825742: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

In [2]:
sent = [
    'the glass of mile',
    'the glass of  juice',
    'the cup of tea',
    'I am a good boy',
    'T am a Good Developer',
    'understanding the meaning of words',
    'your videos are good'
]

In [3]:
## vocabulaze size 
voc_size = 500 # represents the total number of unique word in the entire sentences

### One HOt Representation

In [4]:
onehot_repr = [one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[12, 72, 71, 473], [12, 72, 71, 20], [12, 116, 71, 319], [127, 36, 138, 149, 286], [464, 36, 138, 149, 69], [419, 12, 356, 71, 179], [269, 135, 347, 149]]


### Word Embedding Representation

In [5]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np

In [6]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0  12  72  71 473]
 [  0   0   0   0  12  72  71  20]
 [  0   0   0   0  12 116  71 319]
 [  0   0   0 127  36 138 149 286]
 [  0   0   0 464  36 138 149  69]
 [  0   0   0 419  12 356  71 179]
 [  0   0   0   0 269 135 347 149]]


In [7]:
n_features = 10 # vactotr of size 10 will be used to represent each index from embedded_docs

In [18]:
model = Sequential()
model.add(Embedding(voc_size,10,input_shape=(sent_length,)))
model.compile('adam','mse')

In [19]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (None, 8, 10)          │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
embedded_docs[0]

array([  0,   0,   0,   0,  12,  72,  71, 473], dtype=int32)

In [21]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step
[[[-0.01681559 -0.00681357  0.01691589 -0.00613786  0.04713121
   -0.04220661  0.03299112 -0.04420492  0.01008856 -0.0365288 ]
  [-0.01681559 -0.00681357  0.01691589 -0.00613786  0.04713121
   -0.04220661  0.03299112 -0.04420492  0.01008856 -0.0365288 ]
  [-0.01681559 -0.00681357  0.01691589 -0.00613786  0.04713121
   -0.04220661  0.03299112 -0.04420492  0.01008856 -0.0365288 ]
  [-0.01681559 -0.00681357  0.01691589 -0.00613786  0.04713121
   -0.04220661  0.03299112 -0.04420492  0.01008856 -0.0365288 ]
  [-0.04615529 -0.02525228 -0.01228027  0.01767262  0.00014307
    0.04501809 -0.01790845 -0.00220859 -0.00355202  0.03847348]
  [ 0.01325068  0.00994186 -0.01848272 -0.02829023  0.04922298
    0.03408655 -0.04869545  0.0340653  -0.04834715 -0.04150177]
  [-0.04033764 -0.00941318 -0.01871694 -0.04939158  0.01992724
   -0.0261945   0.01392033 -0.00999005  0.01744746 -0.00565107]
  [ 0.0166938  -0.02824703 -0.03450225 -0.01617266  0.0376523
   -0.00928

## assignment

In [23]:
### assignment

sent =[
    'the world is a better place',
    'Batman series in my favourite movie',
    'I like DC movies',
    'the cat is eating the food',
    'tom and jerry is my favorite movie'
]

In [27]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential

In [28]:
#voc_size
voc_size = 999
sent_one_hot = [one_hot(words,voc_size) for words in sent]
print(sent_one_hot)

[[12, 704, 681, 138, 400, 866], [894, 376, 968, 211, 874, 659], [127, 659, 982, 40], [12, 72, 681, 885, 12, 368], [673, 598, 178, 681, 211, 536, 659]]


In [29]:
# padding 
sent_length = 10
n_features = 12
embedded_sents = pad_sequences(sent_one_hot,padding='pre',maxlen=sent_length)
print(embedded_sents)

[[  0   0   0   0  12 704 681 138 400 866]
 [  0   0   0   0 894 376 968 211 874 659]
 [  0   0   0   0   0   0 127 659 982  40]
 [  0   0   0   0  12  72 681 885  12 368]
 [  0   0   0 673 598 178 681 211 536 659]]


In [30]:
# word embedding using embedding layers

model = Sequential()
model.add(Embedding(voc_size,n_features,input_shape=(sent_length,)))
model.compile('adam','mse')

/home/harry/Documents/Code/Data_Science/DeepLearning/.venv_tf/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [31]:
model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ (None, 10, 12)         │        11,988 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,988 (46.83 KB)

 Trainable params: 11,988 (46.83 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
embedded_sents[0]

array([  0,   0,   0,   0,  12, 704, 681, 138, 400, 866], dtype=int32)

In [34]:
model.predict(embedded_sents)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step


array([[[-4.36594337e-03,  2.28638090e-02,  4.35136296e-02,
         -1.66909322e-02,  4.08721678e-02, -3.86744961e-02,
          1.95290484e-02,  2.84264199e-02, -2.22947840e-02,
          1.30453818e-02,  4.67392243e-02,  3.26545723e-02],
        [-4.36594337e-03,  2.28638090e-02,  4.35136296e-02,
         -1.66909322e-02,  4.08721678e-02, -3.86744961e-02,
          1.95290484e-02,  2.84264199e-02, -2.22947840e-02,
          1.30453818e-02,  4.67392243e-02,  3.26545723e-02],
        [-4.36594337e-03,  2.28638090e-02,  4.35136296e-02,
         -1.66909322e-02,  4.08721678e-02, -3.86744961e-02,
          1.95290484e-02,  2.84264199e-02, -2.22947840e-02,
          1.30453818e-02,  4.67392243e-02,  3.26545723e-02],
        [-4.36594337e-03,  2.28638090e-02,  4.35136296e-02,
         -1.66909322e-02,  4.08721678e-02, -3.86744961e-02,
          1.95290484e-02,  2.84264199e-02, -2.22947840e-02,
          1.30453818e-02,  4.67392243e-02,  3.26545723e-02],
        [ 3.79925482e-02,  3.5444293

# Assignment 2. IMDB Movie Review Dataset

In [36]:
import kagglehub
import os
# Download latest version
path = kagglehub.dataset_download("lakshmi25npathi/imdb-dataset-of-50k-movie-reviews")

print("Path to dataset files:", os.listdir(path))

Path to dataset files: ['IMDB Dataset.csv']


In [37]:
import pandas as pd
df = pd.read_csv(f'{path}/IMDB Dataset.csv')
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [38]:
sentences = df['review']

In [39]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [ ]:
# ONe hot representation
voc_size = 10000
one_hot_review = [one_hot(words,voc_size) for words in sentences]