In [1]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
np.__version__


'1.24.3'

In [3]:
my_arr = np.array([2,4,8,16])
print(my_arr)
print(type(my_arr))

[ 2  4  8 16]
<class 'numpy.ndarray'>


In [4]:
np.array([2,3.4,"str"])

array(['2', '3.4', 'str'], dtype='<U32')

In [5]:
np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.zeros(5,dtype = int)

array([0, 0, 0, 0, 0])

In [8]:
np.ones((3,5,2), dtype=float)

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [9]:
np.arange(1,31,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [10]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.random.random((3,3))

array([[0.12777732, 0.31745511, 0.74031987],
       [0.73096579, 0.24412158, 0.71257998],
       [0.51048228, 0.40422529, 0.61555598]])