In [1]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
np.__version__


'1.24.3'

In [3]:
my_arr = np.array([2,4,8,16])
print(my_arr)
print(type(my_arr))

[ 2  4  8 16]
<class 'numpy.ndarray'>


In [4]:
np.array([2,3.4,"str"])

array(['2', '3.4', 'str'], dtype='<U32')

In [5]:
np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.zeros(5,dtype = int)

array([0, 0, 0, 0, 0])

In [8]:
np.ones((3,5,2), dtype=float)

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [9]:
np.arange(1,31,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [10]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.random.random((3,3))

array([[0.12777732, 0.31745511, 0.74031987],
       [0.73096579, 0.24412158, 0.71257998],
       [0.51048228, 0.40422529, 0.61555598]])

In [3]:
np.random.normal(0,1,(3,3))

array([[-1.04401714,  0.87745288, -0.2592519 ],
       [ 1.56581414, -1.01538356, -1.92155816],
       [-0.77264832, -0.04233266, -1.20786751]])

In [4]:
np.random.randint(0,10,(3,3))

array([[0, 6, 1],
       [3, 7, 6],
       [2, 1, 1]])

In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
x1 = np.random.randint(10,size = 6)
x2 = np.random.randint(10,size = (4,3))
x3 = np.random.randint(10,size = (2,3,4))
x3

array([[[3, 4, 7, 8],
        [4, 7, 6, 1],
        [5, 3, 8, 5]],

       [[3, 8, 5, 1],
        [1, 3, 2, 6],
        [0, 3, 9, 9]]])

In [12]:

print(x1.ndim)
print(x2.ndim)
print(x3.ndim)

1
2
3


In [13]:
print(x1.shape)
print(x2.shape)
print(x3.shape)

(6,)
(4, 3)
(2, 3, 4)


In [14]:
print(x1.size)
print(x2.size)
print(x3.size)

6
12
24


In [18]:
x4=np.random.randint(0,10,(5,2))

In [19]:
print(x4.ndim)
print(x4.shape)
print(x4.size)

2
(5, 2)
10


In [20]:
x4.dtype

dtype('int64')

In [22]:
print('x4.itemsize =',x4.itemsize)
print('x4.nbytes =',x4.nbytes)

x4.itemsize = 8
x4.nbytes = 80


In [36]:
x5 =np.random.randint(0,10,(5,5))
x5.astype(float) # converted to float forcefully

array([[5., 0., 7., 9., 2.],
       [8., 1., 5., 0., 1.],
       [3., 2., 0., 7., 5.],
       [0., 8., 8., 4., 2.],
       [9., 9., 9., 1., 5.]])

In [26]:
print(x5[0,0])
print(x5[2,-1])

4
8


In [27]:
print(x5[4,2])

9


In [28]:
print(x5[-1,2])

9


In [30]:
x5[2,-1]=-3
x5

array([[ 4,  2,  2,  4,  9],
       [ 4,  5,  0,  7,  3],
       [ 8,  3,  5,  5, -3],
       [ 2,  7,  2,  2,  4],
       [ 8,  2,  9,  8,  2]])

In [34]:
np.random.rand(3,3)

array([[0.02470257, 0.21061671, 0.04287289],
       [0.26167957, 0.50068186, 0.53790412],
       [0.70024635, 0.99227999, 0.14857838]])

In [39]:
np.array([[3,4,2],
[4,7,6]])

array([[3, 4, 2],
       [4, 7, 6]])