In [1]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np
np.__version__


'1.24.3'

In [3]:
my_arr = np.array([2,4,8,16])
print(my_arr)
print(type(my_arr))

[ 2  4  8 16]
<class 'numpy.ndarray'>


In [4]:
np.array([2,3.4,"str"])

array(['2', '3.4', 'str'], dtype='<U32')

In [5]:
np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.zeros(5,dtype = int)

array([0, 0, 0, 0, 0])

In [8]:
np.ones((3,5,2), dtype=float)

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [9]:
np.arange(1,31,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [10]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.random.random((3,3))

array([[0.12777732, 0.31745511, 0.74031987],
       [0.73096579, 0.24412158, 0.71257998],
       [0.51048228, 0.40422529, 0.61555598]])

In [3]:
np.random.normal(0,1,(3,3))

array([[-1.04401714,  0.87745288, -0.2592519 ],
       [ 1.56581414, -1.01538356, -1.92155816],
       [-0.77264832, -0.04233266, -1.20786751]])

In [4]:
np.random.randint(0,10,(3,3))

array([[0, 6, 1],
       [3, 7, 6],
       [2, 1, 1]])

In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
x1 = np.random.randint(10,size = 6)
x2 = np.random.randint(10,size = (4,3))
x3 = np.random.randint(10,size = (2,3,4))
x3

array([[[3, 4, 7, 8],
        [4, 7, 6, 1],
        [5, 3, 8, 5]],

       [[3, 8, 5, 1],
        [1, 3, 2, 6],
        [0, 3, 9, 9]]])

In [12]:

print(x1.ndim)
print(x2.ndim)
print(x3.ndim)

1
2
3


In [13]:
print(x1.shape)
print(x2.shape)
print(x3.shape)

(6,)
(4, 3)
(2, 3, 4)


In [14]:
print(x1.size)
print(x2.size)
print(x3.size)

6
12
24


In [18]:
x4=np.random.randint(0,10,(5,2))

In [19]:
print(x4.ndim)
print(x4.shape)
print(x4.size)

2
(5, 2)
10


In [20]:
x4.dtype

dtype('int64')

In [22]:
print('x4.itemsize =',x4.itemsize)
print('x4.nbytes =',x4.nbytes)

x4.itemsize = 8
x4.nbytes = 80


In [36]:
x5 =np.random.randint(0,10,(5,5))
x5.astype(float) # converted to float forcefully

array([[5., 0., 7., 9., 2.],
       [8., 1., 5., 0., 1.],
       [3., 2., 0., 7., 5.],
       [0., 8., 8., 4., 2.],
       [9., 9., 9., 1., 5.]])

In [26]:
print(x5[0,0])
print(x5[2,-1])

4
8


In [27]:
print(x5[4,2])

9


In [28]:
print(x5[-1,2])

9


In [30]:
x5[2,-1]=-3
x5

array([[ 4,  2,  2,  4,  9],
       [ 4,  5,  0,  7,  3],
       [ 8,  3,  5,  5, -3],
       [ 2,  7,  2,  2,  4],
       [ 8,  2,  9,  8,  2]])

In [34]:
np.random.rand(3,3)

array([[0.02470257, 0.21061671, 0.04287289],
       [0.26167957, 0.50068186, 0.53790412],
       [0.70024635, 0.99227999, 0.14857838]])

In [3]:
 x = np.array([[3,4,2],
[4,7,6]])

this is 4 octuber and array slicing and indexing in numpy

In [7]:
x[:2,:3] # rows = index 0 to 2 ; columns = o to 1

array([[3, 4, 2],
       [4, 7, 6]])

In [8]:
x[::2,:] # every other row: all coumns

array([[3, 4, 2]])

In [9]:
x[::-1,::-1] #reverst the entiere matrix

array([[6, 7, 4],
       [2, 4, 3]])

In [10]:
x[:,1]

array([4, 7])

In [11]:
x[1,:]

array([4, 7, 6])

In [13]:
np.arange(1,17).reshape((8,2)) # size of original array must match the size fo the reshaped array

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [14]:
x = np.arange(5)

In [15]:
x.shape

(5,)

In [17]:
x.reshape(1,5) #reshape to 1 x 5 matrix(row matrix) -- 2 dim array

array([[0, 1, 2, 3, 4]])

array concatenation and splitting

In [18]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [19]:
z = [7,8,9]
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#concatenate 2 dim arrays along first axis(rows)
arr2d = np.array([[1,2,3],
                 [4,5,6]])
np.concatenate([arr2d,arr2s])#axix = 0 by default = means concatente along axis 0 (row)
#np.concatenate([arr2d,arr2s],axis=1) # now this will concatenate along axis 1 (columns)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [26]:
#np.split
x = [1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(x,[3,5])#np.split(array, list fo indices split points)
print(x1,x2,x3)


[1 2 3] [99 99] [3 2 1]


In [27]:
grid = np.arange(16).reshape((4,4))

In [29]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
#np.vsplit
upper , lower = np.vsplit(grid,[2]) #np.vsplit(arr,split index)
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [31]:
#np.hsplit
left , right = np.hsplit(grid,[2]) #np.vsplit(arr,split index)
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [32]:
x = np.array([-2,3,10,-3,-1])
abs(x) # onvets negative values into positive

array([ 2,  3, 10,  3,  1])

In [33]:
print(np.absolute(x)) #numpy absolute function
print(np.abs(x)) # alias of np.abxolute

[ 2  3 10  3  1]
[ 2  3 10  3  1]


In [36]:
x = np.arange(2,11)
np.multiply.outer(x,x) # outer product of (u,u) = u*transpose(v); assumingu and v are columns vectros

array([[  4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  8,  12,  16,  20,  24,  28,  32,  36,  40],
       [ 10,  15,  20,  25,  30,  35,  40,  45,  50],
       [ 12,  18,  24,  30,  36,  42,  48,  54,  60],
       [ 14,  21,  28,  35,  42,  49,  56,  63,  70],
       [ 16,  24,  32,  40,  48,  56,  64,  72,  80],
       [ 18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [57]:
# sum of all elements in an array using built-in python sum function
arr = np.random.random(50)
print(arr)

[0.19066578 0.80006024 0.58487335 0.11774956 0.80771289 0.30103868
 0.56347879 0.66334766 0.30560577 0.69223854 0.3822082  0.49337817
 0.68417215 0.53828584 0.72569836 0.66648285 0.94511073 0.53572722
 0.85238366 0.33472559 0.37325793 0.8784155  0.70539077 0.83267165
 0.92796873 0.49116995 0.68509325 0.17448498 0.95787549 0.88653429
 0.32853986 0.35882439 0.66217675 0.41143278 0.34592153 0.02641153
 0.80962706 0.77309669 0.39717702 0.75640154 0.61927805 0.7566958
 0.36684379 0.70937578 0.66772174 0.79175819 0.2005451  0.376942
 0.6702695  0.90869704]


In [58]:
np.sum(arr)

29.035542714299044

In [59]:
np.min(arr)

0.026411530659310234

In [60]:
np.max(arr)

0.957875491091581

In [61]:
np.mean(arr)

0.5807108542859809

In [1]:
import numpy as np
arr = np.random.random(50)
sum(arr)

22.234430568886527

In [2]:
np.sum(arr)

22.234430568886523

In [4]:
big_arr =np.random.rand(1000000)
%timeit sum(big_arr)
%timeit np.sum(big_arr)

63.2 ms ± 2.75 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
615 µs ± 25.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [2]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])

In [3]:
md_arr = np.ones((3,3))
md_arr 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
x #one dimensional array

array([1, 2, 3])

In [6]:
 md_arr + x #broadcasting

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [4]:
X = np.random.random((10,3)) #10*3 array 
X[:5]

array([[0.87816018, 0.86271068, 0.96876238],
       [0.58708959, 0.35550203, 0.59966649],
       [0.49648915, 0.19993081, 0.08899888],
       [0.95768075, 0.99892177, 0.89726902],
       [0.38001492, 0.53044207, 0.74252713]])

In [6]:
X_mean = X.mean(axis = 0) #mean od each colum(features)
X_mean

array([0.61213795, 0.62634971, 0.59701813])

In [8]:
X_centered = X - X_mean #x is centered meaning that the mean of each column

In [9]:
X_centered.mean(axis=0)


array([-4.44089210e-17, -7.77156117e-17,  0.00000000e+00])

In [12]:
x = np.array([[5,0,3,3],
             [7,9,3,5],
             [2,4,7,6]])
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [13]:
np.count_nonzero(x<5)

6

In [14]:
np.count_nonzero(x<5,axis = 1)

array([3, 1, 2])

In [15]:
np.any(x>8)

True

In [16]:
np.any(x<0)

False

In [17]:
np.all(x<0)

False

In [18]:
np.all(x<8,axis = 1)

array([ True, False,  True])

wheateh conunting 

In [1]:
import numpy as np
import pandas as pd


In [2]:

data = pd.read_csv('seattle_weather/seattle-weather.csv')
data.head()

date  precipitation  temp_max  temp_min  wind  weather
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1  2012-01-02           10.9      10.6       2.8   4.5     rain
2  2012-01-03            0.8      11.7       7.2   2.3     rain
3  2012-01-04           20.3      12.2       5.6   4.7     rain
4  2012-01-05            1.3       8.9       2.8   6.1     rain

In [14]:
Date = data["date"]
Date.head()

0    2012-01-01
1    2012-01-02
2    2012-01-03
3    2012-01-04
4    2012-01-05
Name: date, dtype: object

In [12]:
data.shape

(1461, 6)

In [13]:
data.size

8766

In [15]:
data.describe() # this will only work with numerical values

precipitation     temp_max     temp_min         wind
count    1461.000000  1461.000000  1461.000000  1461.000000
mean        3.029432    16.439083     8.234771     3.241136
std         6.680194     7.349758     5.023004     1.437825
min         0.000000    -1.600000    -7.100000     0.400000
25%         0.000000    10.600000     4.400000     2.200000
50%         0.000000    15.600000     8.300000     3.000000
75%         2.800000    22.200000    12.200000     4.000000
max        55.900000    35.600000    18.300000     9.500000

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   date           1461 non-null   object 
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   object 
dtypes: float64(4), object(2)
memory usage: 68.6+ KB


In [3]:
data.describe(include = 'all') #the will work for all categorical value 

date  precipitation     temp_max     temp_min         wind  \
count         1461    1461.000000  1461.000000  1461.000000  1461.000000   
unique        1461            NaN          NaN          NaN          NaN   
top     2012-01-01            NaN          NaN          NaN          NaN   
freq             1            NaN          NaN          NaN          NaN   
mean           NaN       3.029432    16.439083     8.234771     3.241136   
std            NaN       6.680194     7.349758     5.023004     1.437825   
min            NaN       0.000000    -1.600000    -7.100000     0.400000   
25%            NaN       0.000000    10.600000     4.400000     2.200000   
50%            NaN       0.000000    15.600000     8.300000     3.000000   
75%            NaN       2.800000    22.200000    12.200000     4.000000   
max            NaN      55.900000    35.600000    18.300000     9.500000   

       weather  
count     1461  
unique       5  
top       rain  
freq       641  
mean       NaN  
std        NaN  
min        NaN  
25%        NaN  
50%        NaN  
75%        NaN  
max        NaN

In [4]:
data.tail(10)

date  precipitation  temp_max  temp_min  wind weather
1451  2015-12-22            4.6       7.8       2.8   5.0    rain
1452  2015-12-23            6.1       5.0       2.8   7.6    rain
1453  2015-12-24            2.5       5.6       2.2   4.3    rain
1454  2015-12-25            5.8       5.0       2.2   1.5    rain
1455  2015-12-26            0.0       4.4       0.0   2.5     sun
1456  2015-12-27            8.6       4.4       1.7   2.9    rain
1457  2015-12-28            1.5       5.0       1.7   1.3    rain
1458  2015-12-29            0.0       7.2       0.6   2.6     fog
1459  2015-12-30            0.0       5.6      -1.0   3.4     sun
1460  2015-12-31            0.0       5.6      -2.1   3.5     sun

In [7]:
data.sort_values(by=['date']) # this method is used the most while sorting 

date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [8]:
x = np.array([3,4,-4,0,8])

In [9]:
np.sort(x) #return a new sorted array | this is not a permament change

array([-4,  0,  3,  4,  8])

In [10]:
x

array([ 3,  4, -4,  0,  8])

In [11]:
x.sort()
x

array([-4,  0,  3,  4,  8])

In [12]:
x = np.array([2,3,-2,7,0])
np.argsort(x)#returns the indices of sorted elements

array([2, 4, 0, 1, 3])

In [15]:
rand = np.random.RandomState(42)
X = rand.randint(0,10,(4,6)) # this creates 4 * 6 matrixs

In [14]:
X

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [17]:
np.sort(X, axis = 0) #sort each column of x

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [18]:
np.sort(X, axis = 1) #sort each row of x

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [20]:
x= np.array([7,2,3,1,6,5,4])
print(x)
np.partition(x,3)# the first 3 elements in the returned arrays arthe smallest

[7 2 3 1 6 5 4]


array([2, 1, 3, 4, 6, 5, 7])

In [21]:
name = ['Alice','Bob','Cathy','Steve']
age = [ 35,42,25,15]
weight =[60.3,80.2,75.1,51,0]

In [24]:
df = np.zeros(4,dtype={'names':('name','age','weight'),
                      'formats':('U10','i4','f8')})
df.dtype

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [25]:
df

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])